export const FLAG_MAP: Record<string, string> = {
  // Europe
  'Germany': '🇩🇪',
  'France': '🇫🇷',
  'Spain': '🇪🇸',
  'Portugal': '🇵🇹',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Italy': '🇮🇹',
  'Croatia': '🇭🇷',
  'Switzerland': '🇨🇭',
  'Denmark': '🇩🇰',
  'Austria': '🇦🇹',
  'Serbia': '🇷🇸',
  'Poland': '🇵🇱',
  'Slovakia': '🇸🇰',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Turkey': '🇹🇷',
  'Türkiye': '🇹🇷',
  'Ukraine': '🇺🇦',
  'Hungary': '🇭🇺',
  'Czech Republic': '🇨🇿',
  'Czechia': '🇨🇿',
  'Romania': '🇷🇴',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Greece': '🇬🇷',
  'Slovenia': '🇸🇮',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Albania': '🇦🇱',
  'Kosovo': '🇽🇰',
  'Finland': '🇫🇮',
  'Iceland': '🇮🇸',

  // South America
  'Argentina': '🇦🇷',
  'Brazil': '🇧🇷',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Ecuador': '🇪🇨',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Venezuela': '🇻🇪',
  'Paraguay': '🇵🇾',
  'Bolivia': '🇧🇴',

  // North & Central America + Caribbean
  'United States': '🇺🇸',
  'USA': '🇺🇸',
  'Mexico': '🇲🇽',
  'Canada': '🇨🇦',
  'Panama': '🇵🇦',
  'Costa Rica': '🇨🇷',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'El Salvador': '🇸🇻',
  'Trinidad and Tobago': '🇹🇹',

  // Africa
  'Morocco': '🇲🇦',
  'Senegal': '🇸🇳',
  'Nigeria': '🇳🇬',
  'Egypt': '🇪🇬',
  'South Africa': '🇿🇦',
  "Côte d'Ivoire": '🇨🇮',
  'Ivory Coast': '🇨🇮',
  'Cameroon': '🇨🇲',
  'Ghana': '🇬🇭',
  'Tunisia': '🇹🇳',
  'Algeria': '🇩🇿',
  'Mali': '🇲🇱',
  'DR Congo': '🇨🇩',
  'Congo DR': '🇨🇩',
  'Zambia': '🇿🇲',
  'Tanzania': '🇹🇿',
  'Uganda': '🇺🇬',
  'Zimbabwe': '🇿🇼',
  'Comoros': '🇰🇲',
  'Cape Verde': '🇨🇻',
  'Mozambique': '🇲🇿',
  'Namibia': '🇳🇦',
  'Angola': '🇦🇴',
  'Gabon': '🇬🇦',
  'Guinea': '🇬🇳',
  'Equatorial Guinea': '🇬🇶',
  'Burkina Faso': '🇧🇫',

  // Asia & Oceania
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Korea Republic': '🇰🇷',
  'Australia': '🇦🇺',
  'Saudi Arabia': '🇸🇦',
  'Iran': '🇮🇷',
  'IR Iran': '🇮🇷',
  'Qatar': '🇶🇦',
  'Uzbekistan': '🇺🇿',
  'Jordan': '🇯🇴',
  'Iraq': '🇮🇶',
  'United Arab Emirates': '🇦🇪',
  'Oman': '🇴🇲',
  'Bahrain': '🇧🇭',
  'Kuwait': '🇰🇼',
  'China PR': '🇨🇳',
  'China': '🇨🇳',
  'Indonesia': '🇮🇩',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Palestine': '🇵🇸',
  'New Zealand': '🇳🇿',
  'North Korea': '🇰🇵',
  'DPR Korea': '🇰🇵',
}

export function getFlag(teamName: string): string {
  return FLAG_MAP[teamName] ?? ''
}
