// ISO 3166-1 alpha-2 codes — used with flagcdn.com/w40/{code}.png
export const FLAG_MAP: Record<string, string> = {
  // Europe
  'Germany': 'de',
  'France': 'fr',
  'Spain': 'es',
  'Portugal': 'pt',
  'England': 'gb-eng',
  'Netherlands': 'nl',
  'Belgium': 'be',
  'Italy': 'it',
  'Croatia': 'hr',
  'Switzerland': 'ch',
  'Denmark': 'dk',
  'Austria': 'at',
  'Serbia': 'rs',
  'Poland': 'pl',
  'Slovakia': 'sk',
  'Scotland': 'gb-sct',
  'Turkey': 'tr',
  'Türkiye': 'tr',
  'Ukraine': 'ua',
  'Hungary': 'hu',
  'Czech Republic': 'cz',
  'Czechia': 'cz',
  'Romania': 'ro',
  'Sweden': 'se',
  'Norway': 'no',
  'Greece': 'gr',
  'Slovenia': 'si',
  'Wales': 'gb-wls',
  'Albania': 'al',
  'Kosovo': 'xk',
  'Finland': 'fi',
  'Iceland': 'is',
  'Bosnia and Herzegovina': 'ba',
  'North Macedonia': 'mk',
  'Georgia': 'ge',
  'Bulgaria': 'bg',

  // South America
  'Argentina': 'ar',
  'Brazil': 'br',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Ecuador': 'ec',
  'Chile': 'cl',
  'Peru': 'pe',
  'Venezuela': 've',
  'Paraguay': 'py',
  'Bolivia': 'bo',

  // North & Central America + Caribbean
  'United States': 'us',
  'USA': 'us',
  'Mexico': 'mx',
  'Canada': 'ca',
  'Panama': 'pa',
  'Costa Rica': 'cr',
  'Honduras': 'hn',
  'Jamaica': 'jm',
  'El Salvador': 'sv',
  'Trinidad and Tobago': 'tt',
  'Guatemala': 'gt',
  'Cuba': 'cu',
  'Haiti': 'ht',
  'Curacao': 'cw',

  // Africa
  'Morocco': 'ma',
  'Senegal': 'sn',
  'Nigeria': 'ng',
  'Egypt': 'eg',
  'South Africa': 'za',
  "Côte d'Ivoire": 'ci',
  'Ivory Coast': 'ci',
  'Cameroon': 'cm',
  'Ghana': 'gh',
  'Tunisia': 'tn',
  'Algeria': 'dz',
  'Mali': 'ml',
  'DR Congo': 'cd',
  'Congo DR': 'cd',
  'Zambia': 'zm',
  'Tanzania': 'tz',
  'Uganda': 'ug',
  'Zimbabwe': 'zw',
  'Comoros': 'km',
  'Cape Verde': 'cv',
  'Mozambique': 'mz',
  'Namibia': 'na',
  'Angola': 'ao',
  'Gabon': 'ga',
  'Guinea': 'gn',
  'Equatorial Guinea': 'gq',
  'Burkina Faso': 'bf',
  'Benin': 'bj',
  'Sudan': 'sd',
  'Ethiopia': 'et',

  // Asia & Oceania
  'Japan': 'jp',
  'South Korea': 'kr',
  'Korea Republic': 'kr',
  'Australia': 'au',
  'Saudi Arabia': 'sa',
  'Iran': 'ir',
  'IR Iran': 'ir',
  'Qatar': 'qa',
  'Uzbekistan': 'uz',
  'Jordan': 'jo',
  'Iraq': 'iq',
  'United Arab Emirates': 'ae',
  'Oman': 'om',
  'Bahrain': 'bh',
  'Kuwait': 'kw',
  'China PR': 'cn',
  'China': 'cn',
  'Indonesia': 'id',
  'Thailand': 'th',
  'Vietnam': 'vn',
  'Palestine': 'ps',
  'New Zealand': 'nz',
  'North Korea': 'kp',
  'DPR Korea': 'kp',
  'Kyrgyzstan': 'kg',
  'Tajikistan': 'tj',
  'Myanmar': 'mm',
  'Philippines': 'ph',
  'India': 'in',
}

export function getFlag(teamName: string): string {
  return FLAG_MAP[teamName] ?? ''
}

export function flagUrl(code: string): string {
  if (!code) return ''
  return `https://flagcdn.com/w40/${code}.png`
}
